repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.7.19
    hooks:
      # Update the uv lockfile
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.2
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  # - repo: local
  #   hooks:
  #     - id: mojo-format
  #       name: mojo-format
  #       entry: mojo format
  #       language: system
  #       files: '\.(mojo|🔥)$'
  #       stages: [pre-commit]
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.402
    hooks:
    - id: pyright
