name: CI
on:
  push:
    branches:
      - main
  pull_request: {}

# Do not add permissions here! Configure them at the job level!
permissions: {}

jobs:
  check-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba # ratchet:astral-sh/setup-uv@v6

      - name: update uv.lock
        run: uv lock

      - name: check uv.lock unchanged
        run: |
          git diff --exit-code uv.lock || {
            echo ""
            echo ""
            echo "OOPS! It looks like uv.lock has changed.";
            echo "Please run 'uv lock' locally, review the updates, and commit the changes.";
            echo "Here’s what changed:";
            echo ""
            git diff uv.lock;
            exit 1;
          }

      - name: lint python
        run: uv run ruff check .

      - name: format python
        run: uv run ruff format --check .

      - name: type check python
        run: uv run pyright .

      - name: format mojo
        run: uv run mojo format src/alpha_max_zero/kernels
          
      - name: check mojo formatting unchanged
        run: |
          git diff --exit-code src/alpha_max_zero/kernels || {
            echo ""
            echo ""
            echo "OOPS! It looks like uv.lock has changed.";
            echo "Please run 'uv run mojo format src/alpha_max_zero/kernels' locally, review the updates, and commit the changes.";
            echo "Here’s what changed:";
            echo ""
            git diff src/alpha_max_zero/kernels;
            exit 1;
          }
      
      - name: run pytest
        run: uv run pytest -v
